#define START "_start"
asm(".section .sdata\n"
    ".text\n"
    ".global " START "\n"
    ".type " START ",%function\n" START ":\n"
    ".weak __global_pointer$\n"
    ".hidden __global_pointer$\n"
    ".option push\n"
    ".option norelax\n\t"
    "lla gp, __global_pointer$\n"
    ".option pop\n\t"
    "mv a0, sp\n"
    "andi sp, sp, -16\n\t"
    "tail " START "_c");
